#!/bin/bash

# Determine our OS
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='osx'
fi

if [[ $platform == 'linux' ]]; then
  echo "Doing Linuxy things..."
elif [[ $platform == 'osx' ]]; then
  echo "Doing osxy things..."
  # Install HomeBrew
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  # Install RVM
  \curl -sSL https://get.rvm.io | bash -s stable --ruby
  source /Users/phutchins/.rvm/scripts/rvm
  # Install irssi
  brew install irssi
else
  echo "Unable to detect OS or OS not supported..."
  echo ""
fi
